### PR TITLE
Remove archive dependency

### LINKED ISSUE #21: Remove archive dependency
Who knows if CRAN will ever let archive in, we will have to use R's internal unzip / tar code, or maybe https://github.com/r-lib/zip

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #21

### CODE REVIEW

**Comment by jimhester** [comment]
Gabor if you could take a brief look at this to make sure it looks OK I would appreciate it since you have some familiarity with the particularities of the base archive functions.

**Comment by gaborcsardi** [comment]
Sure, np. A quick comment. `desc` can get `DESCRIPTION` from a package archive, just do `desc::desc(<filename>)`. `get_pkg_name` looks pretty robust though, but I would still move this code over into `desc` if you don't mind.

**Comment by jimhester** [comment]
Sure putting it in desc is fine by me.

**Comment by gaborcsardi** [comment]
I think `fix_tar` is somewhat fragile, so how about just copying over the whole thing? We would need to change the license to GPL temporarily....

**Comment by gaborcsardi** [comment]
Another thing, I think we should use the internal `unzip` and the `zip` package. This will make it sure that the same implementation is used across all platforms, and not some zip tool in the user's path.

**Review by gaborcsardi — COMMENTED** [review]
I added some test cases.

OK, so I would do the following changes. If you are OK with them, I will go ahead and do them, since I am familiar with the code now anyway. :)

- [ ] ~~copy over `tar` from R-devel, and change the license to GPL.~~
- [x] use internal `unzip` and `untar` and the `zip` package, everywhere. I believe that this will fix the test failure as well, the columned returned by `unzip` in list mode seem to vary across platforms or R versions
- [x] `windows_archive` -> `is_windows_archive`
- [x] change `archive_read`, so you don't need to specify the directory to extract to.

**Comment by jimhester** [comment]
Feel free to go ahead and make the changes, just add commits to this branch

**Comment by jimhester** [comment]
The only one I am somewhat hesitant about is using the R-devel tar and changing the license, maybe we hold off there for now

**Comment by gaborcsardi** [comment]
> The only one I am somewhat hesitant about is using the R-devel tar and changing the license, maybe we hold off there for now

Agreed. I am hesitant about that as well. I am not sure what the alternatives are, however. Writing our own implementation? Anyway, we can hold off for now.

**Comment by gaborcsardi** [comment]
OK, all done, except for the copy from `utils`. I think it is good to go.

**Comment by gaborcsardi** [comment]
Hmmm, I'll look at the CI failures.

**Comment by gaborcsardi** [comment]
Unfortunately it seems like `fix_tar` does not work for some R versions

**Comment by gaborcsardi** [comment]
@jimhester if you don't want to copy over `tar` into this package, then we could also create a separate `tar` package that works reliably. I would just copy over the code to this.

An external tar implementation is also possible, but the R implementation has a lot of workarounds for various platform dependent issues, so I think it is best to keep that.

**Comment by jimhester** [comment]
It looks like `tar` versions which don't have the conditional are breaking. I am not exactly sure why this is as my impression was the conditional was the reason it wasn't working as documented.

@hadley Do you have any reservations of changing the license to GPL-3 and using the tar implementation from R-devel directly for this?

**Comment by gaborcsardi** [comment]
@jimhester @hadley I actually already created a `tar` package. It is not fully functional yet, but it is not a lot of work.

**Comment by jimhester** [comment]
So I guess we can close this as this is addressed in #39

**Comment by gaborcsardi** [comment]
@jimhester that PR still imports archive, I think, so not entirely addressed just yet.

**Comment by gaborcsardi** [comment]
Seems like it is not too hard to remove it, though.

**Comment by gaborcsardi** [comment]
@jimhester ideally we could still have nice fast tar/untar and zip/unzip packages, so we don't have to resort to the slow and buggy internal tar. E.g. `build(binary = TRUE)` uses the internal tar by default, so it is quite slow for bigger packages.

But it is not very urgent.

**Comment by gaborcsardi** [comment]
This PR is now very much in conflict with the current untar/unzip implementation, so I am going to close this. The issue is still open: https://github.com/r-lib/pkginstall/issues/21 and I'll submit a new PR.

**Pull request closed without merging**
