### PR TITLE
Remove archive dependency

### PR DESCRIPTION
**Pull request by gaborcsardi**
For now. Once the archive package is on CRAN, we'll use it.

### CODE REVIEW

**Comment by jimhester** [comment]
Wait why is verify_binary now unused, do we verify the binary if valid somewhere else now?

**Comment by gaborcsardi** [comment]
We verify after extraction, with a different function. 

If you verify before then you need to extract twice.

**Comment by jimhester** [comment]
Ok, LGTM then

**Review by jimhester — APPROVED** [review]

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
