### PR TITLE
Omit pkgdepends progress bar in the tests

### PR DESCRIPTION
**Pull request by gaborcsardi**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@jimhester FYI

**Comment by jimhester** [comment]
LGTM, we should also open an issue to have pkginstall respect the option.

Also maybe we should rename the option, dplyr's equivalent option is `dplyr.show_progress`, so maybe this should be `pkg.progress_bar` or `pkg.show_progress`?

**Review by jimhester — APPROVED** [review]

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
I can change the options name, and add support for it in `pkginstall`. How about removing the function argument completely? I think the default is fine, and it is easy to do `withr::with_options()`, and adding arguments to all functions is kind of tedious.

**Comment by jimhester** [comment]
Sure that is fine

**Pull request merged**
